"""Generate 00_System/specs/TRACEABILITY.md from the SRS and the design/test documents.

Owner: Orchestrator. Run: .venv\\Scripts\\python 00_System\\tools\\gen_traceability.py [--check]
A requirement counts as "designed" when its ID appears in a design doc, and as "planned"
when a test plan has a TC-<ID>-nn case (or mentions the ID). Code/test tags are added in P2.
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SRS = ROOT / "00_System/specs/SRS.md"
OUT = ROOT / "00_System/specs/TRACEABILITY.md"
DESIGN = {
    "ICD": ROOT / "00_System/specs/ICD_protocol.md",
    "FW": ROOT / "02_FW/docs/FW_design.md",
    "SW": ROOT / "03_SW/docs/SW_design.md",
    "GUI": ROOT / "03_SW/docs/SW_design_GUI.md",
    "HW": ROOT / "01_HW/wiring.md",
}
TESTS = {
    "FW-TP": ROOT / "02_FW/docs/FW_test_plan.md",
    "SW-TP": ROOT / "03_SW/docs/SW_test_plan.md",
}
ROW = re.compile(r"^\| ((?:SYS|SAF-FW|SAF-SW|FW-[A-Z]+|IF|SW-[A-Z]+|NFR)-\d{3}) \|(.*)$")


def srs_rows() -> list[tuple[str, str, str]]:
    rows = []
    for line in SRS.read_text(encoding="utf-8").splitlines():
        m = ROW.match(line)
        if m:
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            # ID | Requirement | Source | Acceptance | V | MS | Pri
            rows.append((m.group(1), cells[5] if len(cells) > 5 else "", cells[6] if len(cells) > 6 else ""))
    return rows


def count_refs(text: str, rid: str) -> int:
    """Exact references plus range forms 'X-001…006', 'X-001...006', 'X-013/014/015'."""
    n = len(re.findall(rf"(?<![A-Z0-9-]){re.escape(rid)}(?!\d)", text))
    prefix, num = rid.rsplit("-", 1)
    k = int(num)
    for m in re.finditer(rf"(?<![A-Z0-9-]){re.escape(prefix)}-(\d{{3}})(?:…|\.\.\.|–)(\d{{3}})", text):
        if int(m.group(1)) <= k <= int(m.group(2)):
            n += 1
    for m in re.finditer(rf"(?<![A-Z0-9-]){re.escape(prefix)}-(\d{{3}}(?:/\d{{3}})+)", text):
        if num in m.group(1).split("/")[1:]:
            n += 1
    return n


def build() -> str:
    rows = srs_rows()
    design = {k: p.read_text(encoding="utf-8") for k, p in DESIGN.items() if p.exists()}
    tests = {k: p.read_text(encoding="utf-8") for k, p in TESTS.items() if p.exists()}
    out = [
        "# Traceability matrix (generated — do not edit)",
        "",
        "Generated by `00_System/tools/gen_traceability.py` from `SRS.md`, the design documents and the test plans.",
        "Columns: number of references to the requirement ID per document; **TC** = number of `TC-<ID>-nn` test cases.",
        "Code (`Implements:`) and test (`Verifies:`) tags are added from P2 on.",
        "",
    ]
    no_design, no_tc = [], []
    body = ["| Req | MS | Pri | " + " | ".join(design) + " | TC (FW+SW) | Status |",
            "|---|---|---|" + "---|" * len(design) + "---|---|"]
    for rid, ms, pri in rows:
        drefs = [count_refs(t, rid) for t in design.values()]
        tcs = sum(len(re.findall(rf"TC-{re.escape(rid)}-\d+", t)) for t in tests.values())
        tc_ids = set()
        for t in tests.values():
            tc_ids |= set(re.findall(rf"TC-{re.escape(rid)}-\d+", t))
        if sum(drefs) == 0:
            no_design.append(rid)
        if not tc_ids:
            no_tc.append(rid)
        status = "designed + planned" if sum(drefs) and tc_ids else ("NO DESIGN" if not sum(drefs) else "NO TC")
        body.append(f"| {rid} | {ms} | {pri} | " + " | ".join(str(d) for d in drefs) + f" | {len(tc_ids)} | {status} |")
    out += [
        "## Summary",
        "",
        f"- Requirements: **{len(rows)}**",
        f"- Without any design reference: **{len(no_design)}** {', '.join(no_design)}",
        f"- Without a test case: **{len(no_tc)}** {', '.join(no_tc)}",
        f"- Distinct test-case IDs: FW {len(set(re.findall(r'TC-[A-Z-]+-\d{3}-\d+', tests.get('FW-TP', ''))))}, "
        f"SW {len(set(re.findall(r'TC-[A-Z-]+-\d{3}-\d+', tests.get('SW-TP', ''))))}",
        "",
        "## Matrix",
        "",
    ] + body + [""]
    return "\n".join(out)


def main() -> int:
    text = build()
    if "--check" in sys.argv:
        ok = OUT.exists() and OUT.read_text(encoding="utf-8") == text
        print("TRACEABILITY.md up to date" if ok else "TRACEABILITY.md stale")
        return 0 if ok else 1
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(text.split("## Matrix")[0])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
