#!/usr/bin/env python3
"""Reference model of the FW link watchdog (ICD_protocol.md v0.7.4 §9.1, §6.2; SAF-FW-015, SAF-FW-001, D-15, D-47 a).

This docstring is the normative definition behind ``vectors/linkwdg_vectors.json`` (generated by gen_vectors.py).

Definitions
-----------
- *valid command frame*: a CRC-valid frame with TYPE 0x01…0x3F (ICD §3.1); every one restarts the silence timer.
- *silence*: time since the end of the last valid command frame; the watchdog **trips** when the silence reaches
  ``safety.link_timeout_ms`` (checked at ≥ 1 kHz: the reaction starts ≤ timeout + 2 ms; a silence of timeout − 1 ms
  never trips). It trips once per silence period.
- *moving*: motion state MOVE_ABS, JOG, MOVE_UNTIL_LOAD, HOMING or STOPPING (codes 3…7).

At the trip (D-47 a, ICD v0.7.4):
1. **every motion state**: VALID is cleared; if it was 1, EVENT VALID_CLEARED (arg = stop cause LINK_WDG 13) is
   sent — the VALID auto-clear of SAF-FW-001 / ICD §4 SET_VALID.
2. **only while moving** (unchanged since ICD v0.2, SAF-FW-015): controlled stop (driver kept enabled), status bit
   LINK_WDG set, EVENTs LINK_WDG and STOPPED (cause LINK_WDG 13); the move ends with its one MOVE_DONE (reason
   STOPPED 5, ICD §5.4 "every motion ends with exactly one MOVE_DONE"; the vectors cover MOVE_ABS and
   MOVE_UNTIL_LOAD — HOMING adds its own §5.4 homing EVENTs); at the next valid command frame LINK_WDG clears
   (EVENT LINK_RESTORED); no motion restarts.
3. while **not** moving: no stop, no LINK_WDG status bit, no EVENT LINK_WDG / STOPPED / LINK_RESTORED.

EVENT order is not specified (the vectors list the EVENT set). Stdlib only.
"""
from __future__ import annotations

from dataclasses import dataclass, field

MOVING_STATES = ("MOVE_ABS", "JOG", "MOVE_UNTIL_LOAD", "HOMING", "STOPPING")
CAUSE_LINK_WDG = 13
MOVE_DONE_STOPPED = 5


@dataclass
class LinkWdgOutcome:
    trip: bool
    stop: str                                  # "none" | "controlled"
    valid_after: bool
    link_wdg_status: bool                      # DATA / STATUS status bit LINK_WDG after the trip
    events: list[tuple[str, int]] = field(default_factory=list)          # sorted (code, arg)
    after_frame_events: list[tuple[str, int]] = field(default_factory=list)  # at the next valid command frame
    link_wdg_after_frame: bool = False


def silence(motion_state: str, valid: bool, silence_ms: float, link_timeout_ms: int) -> LinkWdgOutcome:
    """Outcome of a PC silence of ``silence_ms`` in ``motion_state`` with VALID = ``valid``."""
    if silence_ms < link_timeout_ms:
        return LinkWdgOutcome(False, "none", valid, False)
    moving = motion_state in MOVING_STATES
    ev: list[tuple[str, int]] = []
    if valid:
        ev.append(("VALID_CLEARED", CAUSE_LINK_WDG))
    if moving:
        ev += [("LINK_WDG", 0), ("STOPPED", CAUSE_LINK_WDG), ("MOVE_DONE", MOVE_DONE_STOPPED)]
    return LinkWdgOutcome(True, "controlled" if moving else "none", False, moving, sorted(ev),
                          [("LINK_RESTORED", 0)] if moving else [], False)
