"""GUI-facing contract of the backend (SW_design §15) as ``typing.Protocol`` classes, plus re-exports of every
dataclass / enum / exception the GUI may use. ``gui`` imports only this module, ``core.protocol_gen`` (name
tables) and ``calc.units`` (SW_design_GUI §8, G-01). D builds GUI-test fakes against these Protocols.

Members belonging to M2–M4 are declared here already; the M1 ``Backend`` implements them as stubs that refuse
with a ``GateResult`` item ``NOT_IMPLEMENTED`` (or raise ``NotImplementedError`` for pure accessors).

Futures are ``concurrent.futures.Future``; the backend returns ``ReleasingFuture`` (a subclass).
Nothing here is a Qt type.

Implements: SW-PLT-002 (backend/GUI separation), SW-PLT-003
"""
from __future__ import annotations

import argparse
from collections.abc import Callable, Mapping, Sequence
from concurrent.futures import Future
from typing import Any, Literal, Protocol, runtime_checkable

from bend_stand.core.errors import (
    BendStandError, CalibrationError, CommandNotExecuted, CommandOutcomeUnknown, CommandTimeout,
    ConfigReadOnly, ConfirmationRequired, FileFormatError, GateRefused, IncompatibleFirmware, LinkError,
    NackError, NotConnected, PreconditionError, RecorderError, SequenceError, TransportError,
)
from bend_stand.core.model import (
    GATE_OK, INDICATOR_KEYS, INDICATOR_UNKNOWN, SW_INDICATOR_KEYS, BackendStatus, BoardConfigFile, BoardStatus,
    CalibrationStatus, ChannelSpec, ClearResult, Compat, ConfirmRequest, DeviceInfo, EndpointInfo, EngineState,
    EventRecord, FwEvent, GateCode, GateId, GateItem, GateResult, HotkeyStatus, Indicator, Indicators,
    InputSpec, Issue, IssueSeverity, LatestSample, LimitConfig, LinkState, LinkStateChange, LinkStats,
    LinkStatus, MotionKind, MotionLimits, MotionStatus, MoveDone, MoveOutcome, OperationStatus, PlotSnapshot,
    RecordingStatus, ResumeIgnored, SafetyStatus, SeqStatus, SeriesMinMax, SessionSettings, Severity,
    StopResult, StreamStatus, TareStatus, TestMarks, ThresholdState, Token, TravelDiffState, VerifyReport,
    WriteItem, WriteStatus, XYSnapshot, bit_names,
)

#: A motion ticket: a future resolved with a ``MoveOutcome`` (SW_design §5.4).
MoveTicket = Future  # Future[MoveOutcome]

#: Event topics of SW_design §15.3 (the bridge maps every topic or ignores it explicitly, G-01b).
TOPICS: tuple[str, ...] = (
    "link.state", "link.compat", "device.info", "device.params", "device.status", "fw.event",
    "stop.issued", "stop.confirmed", "stop.unconfirmed", "indicators.changed", "safety.trip",
    "safety.warning", "safety.thresholds", "safety.no_specimen", "motion.done", "motion.target",
    "motion.dropped", "tare.state", "cal.travel.state", "cal.load.state", "cal.travel.restore",
    "channels.changed", "seq.status", "seq.step_result", "seq.window", "rec.state", "rec.failure",
    "sample.taken", "marks.edited", "resume.ignored", "hotkey.state", "hotkey.test", "report.ready", "log",
)


@runtime_checkable
class EventBusAPI(Protocol):
    def subscribe(self, topic: str, cb: Callable[[EventRecord], None], *, weak: bool = True) -> Token: ...
    def unsubscribe(self, token: Token) -> None: ...
    def history(self, topic: str | None = None, limit: int | None = None) -> list[EventRecord]: ...


@runtime_checkable
class ConfigAPI(Protocol):
    """Board configuration (SW-CFG-001…004, §5.3)."""

    def metas(self) -> Sequence[Any]: ...                     # params_gen.ParamMeta, dictionary order
    def groups(self) -> Sequence[tuple[str, str, tuple[str, ...]]]: ...
    def values(self) -> Mapping[str, Any]: ...                # board values as last read (key → value)
    def locked_keys(self) -> frozenset[str]: ...               # managed by the backend (safety.* session values)
    def check(self, edits: Mapping[str, Any]) -> list[Issue]: ...
    def write_and_verify_async(self, edits: Mapping[str, Any]) -> Future[VerifyReport]: ...
    def read_all_async(self) -> Future[Mapping[str, Any]]: ...
    def save_async(self) -> Future[None]: ...
    def load_async(self) -> Future[Mapping[str, Any]]: ...
    def defaults_async(self) -> Future[Mapping[str, Any]]: ...
    def reboot_async(self) -> Future[None]: ...
    def save_board_config(self, path: str, values: Mapping[str, Any] | None = None) -> None: ...
    def load_board_config(self, path: str) -> BoardConfigFile: ...


@runtime_checkable
class MotionAPI(Protocol):
    """Manual motion (§5.4; M2/M3)."""

    def move_to(self, target_mm: float, *, speed_mm_s: float | None = None,
                accel_mm_s2: float | None = None) -> MoveTicket: ...
    def move_by(self, delta_mm: float, *, speed_mm_s: float | None = None,
                accel_mm_s2: float | None = None) -> MoveTicket: ...
    def jog_start(self, direction: int, speed_mm_s: float) -> None: ...
    def jog_update(self, speed_mm_s: float) -> None: ...
    def jog_stop(self) -> None: ...
    def enable(self) -> GateResult: ...
    def disable(self, *, confirmed: bool = False) -> GateResult: ...
    def home(self, *, load_confirmed: bool = False) -> MoveTicket: ...
    def set_test_zero(self) -> float: ...
    def reset_test_zero(self) -> None: ...
    def set_valid(self, flag: bool) -> GateResult: ...
    def limits(self) -> MotionLimits | None: ...
    def check(self, kind: MotionKind, *, speed_mm_s: float | None = None, accel_mm_s2: float | None = None,
              target_mm: float | None = None) -> GateResult: ...


@runtime_checkable
class LimitsAPI(Protocol):
    def get(self) -> LimitConfig: ...
    def set(self, cfg: LimitConfig) -> list[Issue]: ...
    def thresholds(self) -> ThresholdState: ...
    def recheck_async(self) -> Future[ThresholdState]: ...
    def set_no_specimen_mode(self, on: bool, *, confirmed: bool = False) -> GateResult: ...


@runtime_checkable
class DataViewAPI(Protocol):
    """Thread-safe plot data (§7.5, §15.6)."""

    def snapshot(self, keys: Sequence[str], window_s: float, px_width: int) -> PlotSnapshot: ...
    def xy(self, x_key: str, y_key: str, window_s: float | None = None, max_points: int = 4000, *,
           since: Literal["window", "record", "sequence"] = "window") -> XYSnapshot: ...
    def latest(self, key: str) -> LatestSample: ...
    def sequence_trace(self, max_points: int = 20000) -> XYSnapshot: ...


@runtime_checkable
class ChannelRegistryAPI(Protocol):
    def channels(self) -> Sequence[ChannelSpec]: ...
    def get(self, key: str) -> ChannelSpec: ...


@runtime_checkable
class MarksAPI(Protocol):
    def get(self) -> TestMarks: ...
    def set(self, marks: TestMarks) -> None: ...
    def list_presets(self) -> list[str]: ...
    def save_preset(self, path: str) -> None: ...
    def load_preset(self, path: str) -> TestMarks: ...


@runtime_checkable
class SessionAPI(Protocol):
    def get(self) -> SessionSettings: ...
    def set(self, settings: SessionSettings) -> list[Issue]: ...
    def load(self, path: str) -> SessionSettings: ...
    def save(self, path: str) -> None: ...


@runtime_checkable
class EngineAPI(Protocol):
    """Wizard engine (§9.1)."""

    PHASES: tuple[str, ...]

    def state(self) -> EngineState: ...
    def subscribe(self, cb: Callable[[EngineState], None]) -> Token: ...
    def start(self, **config: Any) -> GateResult: ...
    def continue_(self, inputs: Mapping[str, float] | None = None, *, confirmed: bool = False) -> None: ...
    def repeat(self) -> None: ...
    def cancel(self) -> None: ...


@runtime_checkable
class TareEngineAPI(EngineAPI, Protocol):
    def undo(self) -> GateResult: ...


@runtime_checkable
class LoadCalEngineAPI(EngineAPI, Protocol):
    def finish_early(self) -> None: ...
    def retake(self, i: int) -> None: ...


@runtime_checkable
class CalibrationStoreAPI(Protocol):
    def active_load(self) -> Mapping[str, Any] | None: ...
    def active_travel(self) -> Mapping[str, Any] | None: ...
    def history(self, kind: Literal["load", "travel"]) -> list[str]: ...
    def restore_travel_async(self) -> Future[TravelDiffState]: ...
    def resolve_travel_difference_async(
            self, action: Literal["restore", "keep_board", "ignore_session"]) -> Future[TravelDiffState]: ...


@runtime_checkable
class SequencerAPI(Protocol):
    def new(self) -> Any: ...
    def load(self, path: str) -> Any: ...
    def save(self, seq: Any, path: str) -> None: ...
    def validate(self, seq: Any) -> list[Issue]: ...
    def expand(self, seq: Any) -> Any: ...
    def planned_path(self, seq: Any) -> Any: ...
    def generator_schemas(self) -> Mapping[str, Any]: ...
    def start(self, seq: Any, *, confirmed: bool = False) -> GateResult: ...
    def pause(self) -> StopResult: ...
    def resume(self) -> GateResult: ...
    def stop(self) -> StopResult: ...
    def abort(self) -> StopResult: ...
    def status(self) -> SeqStatus: ...


@runtime_checkable
class ReportAPI(Protocol):
    def build_async(self, rec_dir: str, cal: Any = None, tare: Any = None, bend3p: Any = None) -> Future[Any]: ...
    def list_recordings(self, root: str | None = None) -> list[str]: ...
    def load_result(self, rec_dir: str) -> Any: ...


@runtime_checkable
class SimControlAPI(Protocol):
    """In-process simulator control (§12.4): the frozen tools/README vocabulary v2 + test-only extras."""

    def act(self, action: str, **args: Any) -> dict[str, Any]: ...
    def override_status(self, set_bits: int = 0, clear_bits: int = 0, duration_ms: int = 0) -> None: ...
    def emit_event(self, code: int, arg: int = 0, value: int = 0, value2: int = 0) -> None: ...
    def inject_nack(self, cmd: str, status: int, detail: int = 0, count: int = 1) -> None: ...
    def inject_store_mismatch(self, key: str, stored_value: Any) -> None: ...


@runtime_checkable
class TestHooksAPI(Protocol):
    """Test-only hooks (§12.4 a–h), present with ``BackendSettings(test_hooks=True)``."""

    __test__ = False

    def advance(self, ms: float, step_ms: float = 1.0) -> None: ...
    def wire_log(self) -> list[Any]: ...
    def rx_log(self) -> list[Any]: ...
    def fail_recorder(self, exc: BaseException, after_rows: int = 0) -> None: ...
    def set_free_space(self, nbytes: int | None) -> None: ...
    def stall_thread(self, name: str, ms: float) -> None: ...


@runtime_checkable
class BackendAPI(Protocol):
    """The facade the GUI constructs once (§15.1). Global actions never raise and return in ≤ 5 ms."""

    config: ConfigAPI
    motion: MotionAPI
    limits: LimitsAPI
    data: DataViewAPI
    channels: ChannelRegistryAPI
    marks: MarksAPI
    session: SessionAPI
    tare_engine: TareEngineAPI
    travel_cal: EngineAPI
    load_cal: LoadCalEngineAPI
    calibrations: CalibrationStoreAPI
    sequencer: SequencerAPI
    reports: ReportAPI
    events: EventBusAPI
    sim: SimControlAPI | None
    test_hooks: TestHooksAPI | None

    def start(self) -> None: ...
    def shutdown(self) -> None: ...
    def gui_beat(self) -> None: ...
    def endpoints(self) -> list[EndpointInfo]: ...
    def connect_async(self, endpoint: str) -> Future[DeviceInfo]: ...
    def disconnect_async(self) -> Future[None]: ...
    def stop(self, source: str = "gui") -> StopResult: ...
    def halt(self, source: str = "gui") -> StopResult: ...
    def pause(self, source: str = "gui") -> StopResult: ...
    def resume(self, source: str = "gui") -> GateResult: ...
    def tare(self, window_s: float | None = None) -> GateResult: ...
    def take_sample(self, window_s: float = 1.0) -> GateResult: ...
    def record_start(self) -> GateResult: ...
    def record_stop(self) -> GateResult: ...
    def hotkey_test_start(self, timeout_s: float = 10.0) -> GateResult: ...
    def clear_stop_async(self, *, confirmed: bool = False) -> Future[ClearResult]: ...
    def estop_clear_async(self, *, confirmed: bool) -> Future[ClearResult]: ...
    def fault_clear_async(self) -> Future[ClearResult]: ...
    def stream_start_async(self) -> Future[None]: ...
    def stream_stop_async(self) -> Future[None]: ...
    def status(self) -> BackendStatus: ...


#: Signature of D's entry (``bend_stand.gui.app.run``), B3-20.
GuiRun = Callable[[BackendAPI, argparse.Namespace], int]

PROTOCOLS: tuple[type, ...] = (
    EventBusAPI, ConfigAPI, MotionAPI, LimitsAPI, DataViewAPI, ChannelRegistryAPI, MarksAPI, SessionAPI,
    EngineAPI, TareEngineAPI, LoadCalEngineAPI, CalibrationStoreAPI, SequencerAPI, ReportAPI, SimControlAPI,
    TestHooksAPI, BackendAPI,
)

__all__ = [
    # protocols
    "EventBusAPI", "ConfigAPI", "MotionAPI", "LimitsAPI", "DataViewAPI", "ChannelRegistryAPI", "MarksAPI",
    "SessionAPI", "EngineAPI", "TareEngineAPI", "LoadCalEngineAPI", "CalibrationStoreAPI", "SequencerAPI",
    "ReportAPI", "SimControlAPI", "TestHooksAPI", "BackendAPI", "GuiRun", "MoveTicket", "TOPICS", "PROTOCOLS",
    # model
    "GATE_OK", "INDICATOR_KEYS", "INDICATOR_UNKNOWN", "SW_INDICATOR_KEYS", "BackendStatus", "BoardConfigFile",
    "BoardStatus", "CalibrationStatus", "ChannelSpec", "ClearResult", "Compat", "ConfirmRequest", "DeviceInfo",
    "EndpointInfo", "EngineState", "EventRecord", "FwEvent", "GateCode", "GateId", "GateItem", "GateResult",
    "HotkeyStatus", "Indicator", "Indicators", "InputSpec", "Issue", "IssueSeverity", "LatestSample",
    "LimitConfig", "LinkState", "LinkStateChange", "LinkStats", "LinkStatus", "MotionKind", "MotionLimits",
    "MotionStatus", "MoveDone", "MoveOutcome", "OperationStatus", "PlotSnapshot", "RecordingStatus",
    "ResumeIgnored", "SafetyStatus", "SeqStatus", "SeriesMinMax", "SessionSettings", "Severity", "StopResult",
    "StreamStatus", "TareStatus", "TestMarks", "ThresholdState", "Token", "TravelDiffState", "VerifyReport",
    "WriteItem", "WriteStatus", "XYSnapshot", "bit_names",
    # errors
    "BendStandError", "CalibrationError", "CommandNotExecuted", "CommandOutcomeUnknown", "CommandTimeout",
    "ConfigReadOnly", "ConfirmationRequired", "FileFormatError", "GateRefused", "IncompatibleFirmware",
    "LinkError", "NackError", "NotConnected", "PreconditionError", "RecorderError", "SequenceError",
    "TransportError",
]
