"""PlatformIO pre-script of the target envs (FW_design §2.2): build id + generated-code freshness.

* writes $BUILD_DIR/gen_build/build_info_gen.h with FW_BUILD_DATE "YYYYMMDD-HHMM" (local time,
  INFO.build, ICD §7.1) and FW_GIT_HASH (short hash, "+" if the work tree is dirty); the header is
  rewritten only when its content changes;
* runs `00_System/tools/gen_params.py --check` and fails the build if src/gen is stale
  (FW-CFG-001, IF-010).

Origin: Thrust_Stand_HAW/02_FW/tools/build_info.py @37c8747 (copied, docstring adapted).
Implements: FW-CFG-001, FW-CFG-004 (build id), IF-010
"""
import datetime
import os
import subprocess
import sys

Import("env")  # noqa: F821  (SCons)

PROJECT_DIR = env.subst("$PROJECT_DIR")  # noqa: F821
ROOT = os.path.abspath(os.path.join(PROJECT_DIR, ".."))
GEN_PARAMS = os.path.join(ROOT, "00_System", "tools", "gen_params.py")


def _git_hash() -> str:
    try:
        h = subprocess.run(["git", "rev-parse", "--short=8", "HEAD"], cwd=ROOT,
                           capture_output=True, text=True, timeout=10).stdout.strip()
        dirty = subprocess.run(["git", "status", "--porcelain", "--untracked-files=no"], cwd=ROOT,
                               capture_output=True, text=True, timeout=10).stdout.strip()
        return (h or "nogit") + ("+" if dirty else "")
    except (OSError, subprocess.SubprocessError):
        return "nogit"


def _check_params() -> None:
    r = subprocess.run([sys.executable, GEN_PARAMS, "--check"], cwd=ROOT,
                       capture_output=True, text=True)
    if r.returncode != 0:
        sys.stderr.write(r.stdout + r.stderr)
        sys.stderr.write("\n*** build_info.py: generated code in 02_FW/src/gen is stale -> the "
                         "Integrator runs `python 00_System/tools/gen_params.py` (IF-010)\n")
        env.Exit(1)  # noqa: F821


def _write_header() -> None:
    out_dir = os.path.join(env.subst("$BUILD_DIR"), "gen_build")  # noqa: F821
    os.makedirs(out_dir, exist_ok=True)
    stamp = datetime.datetime.now().strftime("%Y%m%d-%H%M")
    text = ("/* GENERATED by tools/build_info.py - do not edit. */\n"
            "#ifndef BUILD_INFO_GEN_H\n#define BUILD_INFO_GEN_H\n"
            f'#define FW_BUILD_DATE "{stamp}"\n'
            f'#define FW_GIT_HASH "{_git_hash()}"\n'
            "#endif\n")
    path = os.path.join(out_dir, "build_info_gen.h")
    old = None
    if os.path.exists(path):
        with open(path, encoding="ascii") as f:
            old = f.read()
    if old != text:
        with open(path, "w", encoding="ascii", newline="\n") as f:
            f.write(text)
    env.Append(CPPPATH=[out_dir])  # noqa: F821


_check_params()
_write_header()
