"""Unity pre-script of env:native (FW_design §8.4, IF-010): shared vectors -> C headers.

Reads IN PLACE (never copied):
    00_System/tools/vectors/protocol_vectors.json   crc16, frames, streams
    00_System/tools/vectors/check_vectors.json      command-acceptance oracle (ref_cmdcheck)
    00_System/tools/vectors/units_vectors.json      µm <-> steps, speed cap (ICD §0.1)
    00_System/tools/vectors/motion_vectors.json     ramp periods, stop paths, planner (M2, ref_motion.py)
and writes $BUILD_DIR/vectors/vec_{crc,frames,streams,check,units,names}.h (not in the repo).

Consistency gate (build error = stale or mixed combination):
  * every vectors/*.json `icd_version` == PROTO_ICD_VERSION (src/gen/proto_gen.h) and
    `param_dict_hash` == PARAM_DICT_HASH (src/gen/params_gen.h);
  * check_vectors.json `state_schema` in (2, 3), no unknown state key and no retired key set
    (tools/README; D-36: stop_btn_* never set);
  * `gen_params.py --check` and `gen_vectors.py --check` exit 0.

Decoded content is translated into C initialisers with the hand-written ref_codec tables and
gen_params (imported in place, test tooling only), so the FW encoders/decoders are compared with
an independent oracle. Standalone use: python tools/gen_test_vectors.py [--out DIR]

Origin: Thrust_Stand_HAW/02_FW/tools/gen_test_vectors.py @37c8747 (structure; rewritten for the
bend-stand message set, check/units/names vectors and the consistency gate).
Implements: IF-010 (FW side), IF-003, IF-004, FW-CMD-001 (test data)
"""
import hashlib
import json
import os
import re
import struct
import subprocess
import sys

try:
    Import("env")  # noqa: F821
    FW = env.subst("$PROJECT_DIR")  # noqa: F821
    OUT_DIR = os.path.join(env.subst("$BUILD_DIR"), "vectors")  # noqa: F821
    _SCONS = True
except NameError:
    FW = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
    OUT_DIR = os.path.join(FW, ".pio", "build", "native", "vectors")
    if "--out" in sys.argv:
        OUT_DIR = sys.argv[sys.argv.index("--out") + 1]
    _SCONS = False

ROOT = os.path.abspath(os.path.join(FW, ".."))
TOOLS = os.path.join(ROOT, "00_System", "tools")
VEC = os.path.join(TOOLS, "vectors")
sys.path.insert(0, TOOLS)
import gen_params  # noqa: E402
import ref_codec as rc  # noqa: E402

STATE_SCHEMA = 2          # ICD v0.5 keeps schema 2: the stop_btn_* keys stay (F-B-25) but are never set (D-36)
ACCEPTED_SCHEMAS = (2, 3)
RETIRED_KEYS = ("stop_btn_active", "stop_btn_released_ms")
STATE_KEYS = ["params", "motion_state", "enabling_left_ms", "homed", "pos_um", "estop_latched",
              "estop_input_open", "estop_closed_ms", "halt_latched", "stop_btn_active",
              "stop_btn_released_ms", "faults", "fault_causes", "limit_start", "limit_end",
              "afe_stale", "afe_saturated", "raw", "drv_power", "alm_active", "nvm_record_valid",
              "paused"]


def fail(msg):
    sys.stderr.write(f"\n*** gen_test_vectors.py: {msg}\n")
    if _SCONS:
        env.Exit(1)  # noqa: F821
    sys.exit(1)


def c_define(path, name):
    txt = open(path, encoding="utf-8").read()
    m = re.search(r"#define\s+" + name + r"\s+(\S+)", txt)
    if not m:
        fail(f"{name} not found in {path}")
    return m.group(1)


def carr(data):
    if not data:
        return "{0}"
    return "{" + ",".join(f"0x{b:02X}" for b in data) + "}"


def cstr(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def cbool(b):
    return "true" if b else "false"


def i32(v):
    """C literal of an int32 (INT32_MIN cannot be written as a plain negative literal)."""
    v = int(v)
    if v == -0x80000000:
        return "INT32_MIN"
    return str(v)


def bits(names, table):
    return rc.names_to_bits(list(names), table)


def wire_of(tname, value):
    return rc.pvalue_pack(rc.PTYPE_CODE[tname], value)


def write(name, lines, sha):
    os.makedirs(OUT_DIR, exist_ok=True)
    guard = name.upper().replace(".", "_")
    head = [f"/* GENERATED by 02_FW/tools/gen_test_vectors.py from 00_System/tools/vectors (json) - "
            f"do not edit.", f" * vectors SHA-256 {sha} */", f"#ifndef {guard}", f"#define {guard}",
            '#pragma GCC diagnostic ignored "-Wunused-const-variable"',
            '#pragma GCC diagnostic ignored "-Wunused-variable"',
            "#include <stdbool.h>", "#include <stdint.h>", '#include "payload.h"', ""]
    text = "\n".join(head + lines + ["#endif", ""])
    path = os.path.join(OUT_DIR, name)
    old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
    if old != text:
        with open(path, "w", encoding="utf-8", newline="\n") as f:
            f.write(text)


# ---------------------------------------------------------------------------------------------
def gate(jsons):
    gen = os.path.join(FW, "src", "gen")
    icd = c_define(os.path.join(gen, "proto_gen.h"), "PROTO_ICD_VERSION").strip('"')
    h = c_define(os.path.join(gen, "params_gen.h"), "PARAM_DICT_HASH")
    h = int(h.rstrip("uUlL"), 16)
    for name, d in jsons.items():
        if d.get("icd_version") != icd:
            fail(f"{name}.json icd_version {d.get('icd_version')} != PROTO_ICD_VERSION {icd} "
                 "(stale generated headers or vectors: Integrator)")
        if int(d.get("param_dict_hash", "0"), 16) != h:
            fail(f"{name}.json param_dict_hash {d.get('param_dict_hash')} != PARAM_DICT_HASH "
                 f"0x{h:08X} (Integrator)")
    for tool in ("gen_params.py", "gen_vectors.py"):
        r = subprocess.run([sys.executable, os.path.join(TOOLS, tool), "--check"], cwd=ROOT,
                           capture_output=True, text=True)
        if r.returncode != 0:
            sys.stderr.write(r.stdout + r.stderr)
            fail(f"{tool} --check failed: generated outputs are stale (Integrator)")
    return icd, h


# ---------------------------------------------------------------------------------------------
def gen_crc(v):
    out = ["typedef struct { const char *name; const uint8_t *data; uint16_t len; uint16_t crc; } vec_crc_t;"]
    for i, c in enumerate(v["crc16"]):
        out.append(f"static const uint8_t VCRC_{i}[] = {carr(bytes.fromhex(c['input_hex']))};")
    out.append("static const vec_crc_t VEC_CRC[] = {")
    for i, c in enumerate(v["crc16"]):
        out.append(f"    {{{cstr(c['name'])}, VCRC_{i}, {len(bytes.fromhex(c['input_hex']))}u, {c['crc']}u}},")
    out.append("};")
    out.append(f"#define VEC_CRC_N {len(v['crc16'])}u")
    return out


def info_init(d):
    b = d["build"].encode("ascii").ljust(16, b"\x00")
    return (f"{{ {d['proto_major']}u, {d['proto_minor']}u, {d['payload_version']}u, "
            f"{{{d['fw_version'][0]}u, {d['fw_version'][1]}u, {d['fw_version'][2]}u}}, "
            f"{d['param_dict_hash']}u, {carr(bytes.fromhex(d['uid']))}, {carr(b)}, "
            f"{d['param_count']}u, 0x{bits(d['features'], rc.FEATURES):08X}u }}")


def status_init(d):
    def enum(k, table):
        return rc._enum_code(table, d[k])
    f = {
        "uptime_ms": f"{d['uptime_ms']}u", "t_us": f"{d['t_us']}u",
        "flags": f"0x{bits(d['flags'], rc.DATA_FLAGS):02X}u",
        "motion_state": f"{enum('motion_state', rc.MOTION_STATE)}u",
        "status": f"0x{bits(d['status'], rc.DATA_STATUS):04X}u",
        "faults": f"0x{bits(d['faults'], rc.FAULTS):04X}u",
        "io": f"0x{bits(d['io'], rc.IO):04X}u",
        "home_phase": f"{enum('home_phase', rc.HOME_PHASE)}u",
        "halt_src": f"{enum('halt_src', rc.SOURCE)}u",
        "reset_cause": f"{enum('reset_cause', rc.RESET_CAUSE)}u",
        "sys_flags": f"0x{bits(d['sys_flags'], rc.SYS_FLAGS):02X}u",
        "pos_um": i32(d["pos_um"]), "target_um": i32(d["target_um"]),
        "pos_steps": i32(d["pos_steps"]), "afe_raw_last": i32(d["afe_raw_last"]),
        "pause_src": f"{enum('pause_src', rc.SOURCE)}u",
    }
    for k in rc.STATUS_FIELDS:
        f.setdefault(k, f"{d[k]}u")
    return "{ " + ", ".join(f".{k} = {f[k]}" for k in rc.STATUS_FIELDS) + " }"


def data_init(d):
    return (f"{{ .t_us = {d['t_us']}u, .flags = 0x{bits(d['flags'], rc.DATA_FLAGS):02X}u, "
            f".afe_raw = {i32(d['afe_raw'])}, .setpoint_um = {i32(d['setpoint_um'])}, "
            f".frame_seq = {d['frame_seq']}u, .status = 0x{bits(d['status'], rc.DATA_STATUS):04X}u }}")


def event_init(d):
    return (f"{{ .t_us = {d['t_us']}u, .code = {rc.EVENT[d['code']]}u, .arg = {d['arg']}u, "
            f".value = {i32(d['value'])}, .value2 = {i32(d['value2'])} }}")


def entry_init(e, raw4=None):
    w = raw4 if raw4 is not None else wire_of(e["type"], e["value"])
    return f"{{ {e['id']}u, {rc.PTYPE_CODE[e['type']]}u, {carr(w)} }}"


def req_init(f):
    d = f["decoded"]
    tn = f["type_name"]
    pl = bytes.fromhex(f["payload_hex"])
    t = f["type"]
    if tn == "REBOOT":
        u = f".u.reboot = {{ {d['magic']}u }}"
    elif tn == "GET_ALL_PARAMS":
        u = f".u.page = {{ {d['page']}u }}"
    elif tn == "GET_PARAM":
        u = f".u.get_param = {{ {d['id']}u }}"
    elif tn == "SET_PARAM":
        # INVALID_PADDING: the vector has no numeric value; the wire bytes are the payload's own
        raw4 = pl[3:7] if d.get("value") == "INVALID_PADDING" else None
        u = f".u.set_param = {entry_init(d, raw4)}"
    elif tn == "SET_VALID":
        u = f".u.set_valid = {{ {d['valid']}u }}"
    elif tn == "HOME":
        u = f".u.home = {{ {d['flags']}u }}"
    elif tn == "MOVE_ABS":
        u = f".u.move_abs = {{ {i32(d['target_um'])}, {d['v_um_s']}u, {d['a_um_s2']}u }}"
    elif tn == "JOG":
        u = f".u.jog = {{ {i32(d['v_um_s'])}, {d['a_um_s2']}u, {i32(d['bound_um'])} }}"
    elif tn == "MOVE_UNTIL_LOAD":
        u = (f".u.mul = {{ {i32(d['bound_um'])}, {d['v_um_s']}u, {d['a_um_s2']}u, "
             f"{i32(d['raw_stop'])}, {d['cmp']}u }}")
    elif tn == "STOP":
        u = f".u.stop = {{ {d['mode']}u }}"
    elif rc.REQ_LEN.get(tn, -1) == 0:
        u = ""
    else:
        fail(f"unhandled request vector {f['name']} ({tn})")
    return f"{{ .type = {t}u{', ' + u if u else ''} }}"


RB = {"NACK": 0, "EMPTY": 1, "INFO": 2, "STATUS": 3, "PAGE": 4, "ENTRY": 5, "U32": 6, "U16": 7}


def gen_frames(v):
    frames = v["frames"]
    out = ["enum { VK_REQUEST = 0, VK_RESPONSE = 1, VK_ASYNC = 2, VK_INVALID = 3 };",
           "typedef struct { const char *name; uint8_t fw_to_pc; uint8_t kind; uint8_t type; uint8_t seq;",
           "    uint16_t len; const uint8_t *frame; uint16_t frame_len; const uint8_t *payload;",
           "    bool reencode; const uint8_t *canon; uint16_t canon_len; bool framing_only;",
           "    uint32_t expect_crc_errors; } vec_frame_t;"]
    kinds = {"request": "VK_REQUEST", "response": "VK_RESPONSE", "async": "VK_ASYNC", "invalid": "VK_INVALID"}
    for i, f in enumerate(frames):
        out.append(f"static const uint8_t VF_{i}[] = {carr(bytes.fromhex(f['frame_hex']))};")
        out.append(f"static const uint8_t VP_{i}[] = {carr(bytes.fromhex(f.get('payload_hex', '')))};")
        if f.get("reencode") is False:
            out.append(f"static const uint8_t VC_{i}[] = {carr(bytes.fromhex(f['canonical_payload_hex']))};")
    out.append("static const vec_frame_t VEC_FRAMES[] = {")
    for i, f in enumerate(frames):
        fr = bytes.fromhex(f["frame_hex"])
        re_ = f.get("reencode") is not False
        canon = "0" if re_ else f"VC_{i}"
        clen = 0 if re_ else len(bytes.fromhex(f["canonical_payload_hex"]))
        out.append(
            f"    {{{cstr(f['name'])}, {1 if f['dir'] == 'fw->pc' else 0}u, {kinds[f['kind']]}, "
            f"{f.get('type', '0x00')}u, {f.get('seq', 0)}u, {f.get('len', 0)}u, VF_{i}, {len(fr)}u, VP_{i}, "
            f"{cbool(re_)}, {canon}, {clen}u, {cbool(f.get('framing_only', False))}, "
            f"{f.get('expect', {}).get('crc_errors', 0)}u}},")
    out.append("};")
    out.append(f"#define VEC_FRAMES_N {len(frames)}u")

    # requests -> expected decoder output
    reqs = [(i, f) for i, f in enumerate(frames)
            if f["kind"] == "request" and not f.get("framing_only") and "raw_hex" not in f["decoded"]]
    out.append("typedef struct { uint16_t idx; cmd_req_t r; } vec_req_t;")
    out.append("static const vec_req_t VEC_REQS[] = {")
    for i, f in reqs:
        out.append(f"    {{ {i}u, {req_init(f)} }},")
    out.append("};")
    out.append(f"#define VEC_REQS_N {len(reqs)}u")

    # responses -> expected body description
    resps = []
    for i, f in enumerate(frames):
        if f["kind"] != "response" or f.get("framing_only"):
            continue
        d = f["decoded"]
        tn = f["type_name"]
        st = d["status"]
        if st != "OK":
            resps.append((i, "NACK", rc.STATUS[st], d["detail"], None))
        elif tn == "GET_INFO":
            resps.append((i, "INFO", 0, 0, d["info"]))
        elif tn == "GET_STATUS":
            resps.append((i, "STATUS", 0, 0, d["board_status"]))
        elif tn == "GET_ALL_PARAMS":
            resps.append((i, "PAGE", 0, 0, d))
        elif tn in ("GET_PARAM", "SET_PARAM"):
            resps.append((i, "ENTRY", 0, 0, d["entry"]))
        elif tn == "SET_VALID":
            resps.append((i, "U32", 0, d["t_us"], None))
        elif tn == "ENABLE":
            resps.append((i, "U16", 0, d["settle_ms"], None))
        elif tn == "FAULT_CLEAR":
            resps.append((i, "U16", 0, bits(d["cleared"], rc.FAULTS), None))
        elif len(d) == 1:
            resps.append((i, "EMPTY", 0, 0, None))
        else:
            fail(f"unhandled response vector {f['name']}")
    for k, (i, kind, _, _, obj) in enumerate(resps):
        if kind == "INFO":
            out.append(f"static const info_t VRI_{k} = {info_init(obj)};")
        elif kind == "STATUS":
            out.append(f"static const status_t VRS_{k} = {status_init(obj)};")
        elif kind == "PAGE":
            out.append(f"static const param_entry_t VRP_{k}[] = {{")
            for e in obj["entries"]:
                out.append(f"    {entry_init(e)},")
            out.append("};")
        elif kind == "ENTRY":
            out.append(f"static const param_entry_t VRE_{k} = {entry_init(obj)};")
    out.append("enum { " + ", ".join(f"RB_{k} = {n}" for k, n in RB.items()) + " };")
    out.append("typedef struct { uint16_t idx; uint8_t kind; uint8_t status; uint32_t num;")
    out.append("    const info_t *info; const status_t *st; const param_entry_t *entries;")
    out.append("    uint8_t page, page_count, n; } vec_resp_t;")
    out.append("static const vec_resp_t VEC_RESPS[] = {")
    for k, (i, kind, st, num, obj) in enumerate(resps):
        info = f"&VRI_{k}" if kind == "INFO" else "0"
        sts = f"&VRS_{k}" if kind == "STATUS" else "0"
        ent = f"VRP_{k}" if kind == "PAGE" else (f"&VRE_{k}" if kind == "ENTRY" else "0")
        page = obj["page"] if kind == "PAGE" else 0
        pc = obj["page_count"] if kind == "PAGE" else 0
        n = len(obj["entries"]) if kind == "PAGE" else (1 if kind == "ENTRY" else 0)
        out.append(f"    {{ {i}u, RB_{kind}, {st}u, {num}u, {info}, {sts}, {ent}, {page}u, {pc}u, {n}u }},")
    out.append("};")
    out.append(f"#define VEC_RESPS_N {len(resps)}u")

    datas = [(i, f) for i, f in enumerate(frames) if f["kind"] == "async" and f["type_name"] == "DATA"]
    events = [(i, f) for i, f in enumerate(frames) if f["kind"] == "async" and f["type_name"] == "EVENT"]
    out.append("typedef struct { uint16_t idx; data_t d; } vec_data_t;")
    out.append("static const vec_data_t VEC_DATAS[] = {" +
               ",".join(f"\n    {{ {i}u, {data_init(f['decoded'])} }}" for i, f in datas) + "\n};")
    out.append(f"#define VEC_DATAS_N {len(datas)}u")
    out.append("typedef struct { uint16_t idx; event_t e; } vec_event_t;")
    out.append("static const vec_event_t VEC_EVENTS[] = {" +
               ",".join(f"\n    {{ {i}u, {event_init(f['decoded'])} }}" for i, f in events) + "\n};")
    out.append(f"#define VEC_EVENTS_N {len(events)}u")
    return out


def gen_streams(v):
    out = ["typedef struct { const char *name; uint8_t n_chunks; const uint8_t *const *chunks;",
           "    const uint16_t *chunk_len; bool idle_timeout_at_end; uint8_t n_before; uint8_t n_frames;",
           "    const uint8_t *const *frames; const uint16_t *frame_len;",
           "    uint32_t frames_ok, crc_errors, len_errors, timeout_drops; } vec_stream_t;"]
    for k, s in enumerate(v["streams"]):
        for j, c in enumerate(s["chunks_hex"]):
            out.append(f"static const uint8_t VSC_{k}_{j}[] = {carr(bytes.fromhex(c))};")
        out.append(f"static const uint8_t *const VSC_{k}[] = {{" +
                   ",".join(f"VSC_{k}_{j}" for j in range(len(s["chunks_hex"]))) + "};")
        out.append(f"static const uint16_t VSCL_{k}[] = {{" +
                   ",".join(f"{len(bytes.fromhex(c))}u" for c in s["chunks_hex"]) + "};")
        for j, fx in enumerate(s["expect_frames_hex"]):
            out.append(f"static const uint8_t VSF_{k}_{j}[] = {carr(bytes.fromhex(fx))};")
        nf = len(s["expect_frames_hex"])
        out.append(f"static const uint8_t *const VSF_{k}[] = {{" +
                   (",".join(f"VSF_{k}_{j}" for j in range(nf)) or "0") + "};")
        out.append(f"static const uint16_t VSFL_{k}[] = {{" +
                   (",".join(f"{len(bytes.fromhex(fx))}u" for fx in s["expect_frames_hex"]) or "0") + "};")
    out.append("static const vec_stream_t VEC_STREAMS[] = {")
    for k, s in enumerate(v["streams"]):
        c = s["expect_counters"]
        nb = len(s["expect_frames_before_timeout"]) if s["expect_frames_before_timeout"] is not None else 255
        out.append(f"    {{ {cstr(s['name'])}, {len(s['chunks_hex'])}u, VSC_{k}, VSCL_{k}, "
                   f"{cbool(s['idle_timeout_at_end'])}, {nb}u, {len(s['expect_frames_hex'])}u, VSF_{k}, "
                   f"VSFL_{k}, {c['frames_ok']}u, {c['crc_errors']}u, {c['len_errors']}u, "
                   f"{c['timeout_drops']}u }},")
    out.append("};")
    out.append(f"#define VEC_STREAMS_N {len(v['streams'])}u")
    return out


def gen_check(v, dic):
    if v.get("state_schema") not in ACCEPTED_SCHEMAS:
        fail(f"check_vectors.json state_schema {v.get('state_schema')} not in {ACCEPTED_SCHEMAS} "
             "(update the FW replay: cmd_ctx_t / this script)")
    by_key = {p.key: p for p in dic.params}
    defaults = v["state_defaults"]
    for x in v["vectors"]:
        if set(RETIRED_KEYS) & set(x["state"]):
            fail(f"check vector {x['name']}: retired state key set (state_schema {STATE_SCHEMA})")
    for k in list(defaults) + [k for x in v["vectors"] for k in x["state"]]:
        if k not in STATE_KEYS:
            fail(f"check_vectors.json: unknown state key {k!r} (state_schema {STATE_SCHEMA})")
    out = ["typedef struct { uint16_t id; uint32_t raw; } vec_pov_t;",
           "typedef struct { const char *name;",
           "    uint8_t motion_state; uint16_t enabling_left_ms; bool homed; int32_t pos_um;",
           "    bool estop_latched, estop_input_open; uint32_t estop_closed_ms;",
           "    bool halt_latched;",
           "    uint16_t faults, fault_causes; bool limit_start, limit_end, afe_stale, afe_saturated;",
           "    int32_t raw; bool drv_power, alm_active, nvm_record_valid, paused;",
           "    uint8_t n_par; const vec_pov_t *par;",
           "    uint8_t type; uint8_t seq; const uint8_t *payload; uint16_t len;",
           "    const uint8_t *req_frame; uint16_t req_frame_len;",
           "    uint8_t exp_status; uint16_t exp_detail; const uint8_t *resp_frame; uint16_t resp_len;",
           "    int8_t paused_after; } vec_check_t;"]
    rows = []
    for k, x in enumerate(v["vectors"]):
        st = dict(defaults)
        st.update(x["state"])
        pars = []
        for key, val in st["params"].items():
            if key not in by_key:
                fail(f"check vector {x['name']}: unknown parameter {key}")
            p = by_key[key]
            pars.append((p.id, gen_params.raw_u32(p, val)))
        if pars:
            out.append(f"static const vec_pov_t VCP_{k}[] = {{" +
                       ",".join(f"{{0x{pid:04X}u,0x{raw:08X}u}}" for pid, raw in pars) + "};")
        rq = x["request"]
        pl = bytes.fromhex(rq["payload_hex"])
        out.append(f"static const uint8_t VCQ_{k}[] = {carr(pl)};")
        out.append(f"static const uint8_t VCF_{k}[] = {carr(bytes.fromhex(rq['frame_hex']))};")
        e = x["expect"]
        resp = bytes.fromhex(e.get("response_frame_hex", ""))
        out.append(f"static const uint8_t VCR_{k}[] = {carr(resp)};")
        pa = e.get("paused_after")
        rows.append(
            f"    {{ {cstr(x['name'])}, {rc.MOTION_STATE.index(st['motion_state'])}u, "
            f"{st['enabling_left_ms']}u, {cbool(st['homed'])}, {i32(st['pos_um'])}, "
            f"{cbool(st['estop_latched'])}, {cbool(st['estop_input_open'])}, {st['estop_closed_ms']}u, "
            f"{cbool(st['halt_latched'])}, "
            f"0x{bits(st['faults'], rc.FAULTS):04X}u, 0x{bits(st['fault_causes'], rc.FAULTS):04X}u, "
            f"{cbool(st['limit_start'])}, {cbool(st['limit_end'])}, {cbool(st['afe_stale'])}, "
            f"{cbool(st['afe_saturated'])}, {i32(st['raw'])}, {cbool(st['drv_power'])}, "
            f"{cbool(st['alm_active'])}, {cbool(st['nvm_record_valid'])}, {cbool(st['paused'])}, "
            f"{len(pars)}u, {('VCP_' + str(k)) if pars else '0'}, {rq['type']}u, {rq['seq']}u, VCQ_{k}, "
            f"{len(pl)}u, VCF_{k}, {len(bytes.fromhex(rq['frame_hex']))}u, {rc.STATUS[e['status']]}u, "
            f"{e['detail']}u, VCR_{k}, {len(resp)}u, {-1 if pa is None else int(bool(pa))} }},")
    out.append("static const vec_check_t VEC_CHECK[] = {")
    out += rows
    out.append("};")
    out.append(f"#define VEC_CHECK_N {len(v['vectors'])}u")
    return out


def f32hex(h):
    return int(h, 16)


def gen_units(v):
    out = ["typedef struct { uint32_t spm_bits; int32_t a; int32_t b; } vec_units_t;",
           "typedef struct { uint32_t spm_bits; uint32_t rate; uint32_t cap; } vec_cap_t;"]
    for name, src, a, b in (("VEC_UM2ST", "um_to_steps", "um", "steps"),
                            ("VEC_ST2UM", "steps_to_um", "steps", "um")):
        out.append(f"static const vec_units_t {name}[] = {{")
        for x in v[src]:
            out.append(f"    {{ 0x{f32hex(x['spm_f32_hex']):08X}u, {i32(x[a])}, {i32(x[b])} }},")
        out.append("};")
        out.append(f"#define {name}_N {len(v[src])}u")
    out.append("static const vec_cap_t VEC_CAP[] = {")
    for x in v["rate_cap"]:
        out.append(f"    {{ 0x{f32hex(x['spm_f32_hex']):08X}u, {x['max_step_rate_hz']}u, {x['rate_cap_um_s']}u }},")
    out.append("};")
    out.append(f"#define VEC_CAP_N {len(v['rate_cap'])}u")
    return out


def gen_motion(v):
    """motion_vectors.json (ref_motion.py oracle, M2): ramp cases, stop paths, planner."""
    kinds = {"controlled_stop": 0, "jog": 1}
    paths = {"ISR": 0, "CLEAN": 1, "STRETCH": 2}
    out = ["typedef struct { uint32_t after; int32_t v_um_s; uint8_t kind; } vec_mev_t;",
           "typedef struct { const char *name; float spm; uint32_t f_tick, v, a, d, a_stop, n_steps;",
           "    uint8_t n_ev; const vec_mev_t *ev; uint32_t n_periods; const uint32_t *periods;",
           "    uint64_t sum; uint32_t tol_p, tol_sum; } vec_motion_t;",
           "typedef struct { uint32_t p_ticks; float spm; uint32_t a_stop; double d_steps; uint8_t path; } vec_spath_t;",
           "typedef struct { uint32_t n; double v, a, d; bool tri; uint32_t n_acc, n_cruise, n_dec;",
           "    double v_peak, t; } vec_plan_t;"]
    for k, c in enumerate(v["cases"]):
        out.append(f"static const uint32_t VMP_{k}[] = {{" + ",".join(f"{p}u" for p in c["periods"]) + "};")
        evs = c["events"]
        if evs:
            out.append(f"static const vec_mev_t VME_{k}[] = {{" + ",".join(
                f"{{{e['after_step']}u, {int(e.get('v_um_s', 0))}, {kinds[e['event']]}u}}" for e in evs) + "};")
    out.append("static const vec_motion_t VEC_MOTION[] = {")
    for k, c in enumerate(v["cases"]):
        evs = c["events"]
        out.append(f"    {{ {cstr(c['name'])}, {float(c['steps_per_mm'])!r}f, {c['f_tick']}u, {c['v_um_s']}u, "
                   f"{c['a_um_s2']}u, {c['d_um_s2']}u, {c['a_stop_um_s2'] or 0}u, {c['n_steps']}u, "
                   f"{len(evs)}u, {('VME_' + str(k)) if evs else '0'}, {c['n_periods']}u, VMP_{k}, "
                   f"{c['sum_ticks']}ull, {c['tolerance']['period_ticks']}u, {c['tolerance']['sum_ticks']}u }},")
    out.append("};")
    out.append(f"#define VEC_MOTION_N {len(v['cases'])}u")
    out.append("static const vec_spath_t VEC_SPATH[] = {")
    for x in v["ctrl_stop_paths"]:
        out.append(f"    {{ {x['p_ticks']}u, {float(x['steps_per_mm'])!r}f, {x['a_stop_um_s2']}u, "
                   f"{float(x['d_steps'])!r}, {paths[x['path']]}u }},")
    out.append("};")
    out.append(f"#define VEC_SPATH_N {len(v['ctrl_stop_paths'])}u")
    out.append("static const vec_plan_t VEC_PLAN[] = {")
    for x in v["planner"]:
        out.append(f"    {{ {x['n_steps']}u, {float(x['v_steps_s'])!r}, {float(x['a_steps_s2'])!r}, "
                   f"{float(x['d_steps_s2'])!r}, {cbool(x['kind'] == 'tri')}, {x['n_acc']}u, {x['n_cruise']}u, "
                   f"{x['n_dec']}u, {float(x['v_peak'])!r}, {float(x['t'])!r} }},")
    out.append("};")
    out.append(f"#define VEC_PLAN_N {len(v['planner'])}u")
    return out


def gen_names():
    """Every generated identifier compared with the hand-written ref_codec tables: a missing or
    renamed macro is a compile error, a different value a test failure (IF-001, GF-08)."""
    rows = []

    def add(prefix, items):
        for n, val in items:
            rows.append(f'    {{ "{prefix}{n}", {val}u, (uint32_t)({prefix}{n}) }},')
    add("CMD_", rc.CMD.items())
    add("ST_", rc.STATUS.items())
    add("EV_", rc.EVENT.items())
    add("SC_", rc.STOP_CAUSE.items())
    for prefix, table in (("DF_", rc.DATA_FLAGS), ("DS_", rc.DATA_STATUS), ("FAULT_", rc.FAULTS),
                          ("BLOCK_", rc.BLOCK), ("IO_", rc.IO), ("SYSF_", rc.SYS_FLAGS),
                          ("FEAT_", rc.FEATURES)):
        add(prefix, [(n, 1 << i) for i, n in enumerate(table) if n])
    for prefix, table in (("MS_", rc.MOTION_STATE), ("HP_", rc.HOME_PHASE), ("SRC_", rc.SOURCE),
                          ("RST_", rc.RESET_CAUSE), ("MD_", rc.MOVE_DONE_REASON)):
        add(prefix, [(n, i) for i, n in enumerate(table)])
    add("HF_", [(n, c) for c, n in rc.HOME_FAIL_REASON.items()])
    consts = [("PROTO_MAX_LEN", rc.MAX_LEN), ("PROTO_HEADER_LEN", rc.HEADER_LEN),
              ("PROTO_FRAME_OVERHEAD", rc.OVERHEAD), ("PROTO_INFO_LEN", rc.INFO_LEN),
              ("PROTO_STATUS_LEN", rc.STATUS_LEN), ("PROTO_DATA_LEN", rc.DATA_LEN),
              ("PROTO_EVENT_LEN", rc.EVENT_LEN), ("PROTO_PARAMS_PER_PAGE", rc.PARAMS_PER_PAGE),
              ("PROTO_REBOOT_MAGIC", rc.REBOOT_MAGIC), ("PROTO_PAYLOAD_VERSION", rc.PAYLOAD_VERSION),
              ("PROTO_MAJOR", rc.PROTO_MAJOR), ("PROTO_MINOR", rc.PROTO_MINOR),
              ("PROTO_INTERBYTE_TIMEOUT_MS", rc.INTERBYTE_TIMEOUT_MS)]
    for n, val in consts:
        rows.append(f'    {{ "{n}", {val}u, (uint32_t)({n}) }},')
    for name in rc.CMD:
        rows.append(f'    {{ "CMD_REQ_LEN_{name}", {rc.REQ_LEN[name]}u, (uint32_t)(CMD_REQ_LEN_{name}) }},')
    out = ["#include \"proto_gen.h\"",
           "typedef struct { const char *name; uint32_t expect; uint32_t actual; } vec_name_t;",
           "static const vec_name_t VEC_NAMES[] = {"] + rows + ["};",
                                                              f"#define VEC_NAMES_N {len(rows)}u"]
    return out


def main():
    jsons = {}
    raw = b""
    for name in ("protocol_vectors", "check_vectors", "units_vectors", "motion_vectors"):
        path = os.path.join(VEC, name + ".json")
        b = open(path, "rb").read()
        raw += b
        jsons[name] = json.loads(b)
    icd, h = gate(jsons)
    sha = hashlib.sha256(raw).hexdigest()
    dic = gen_params.load()
    pv = jsons["protocol_vectors"]
    write("vec_crc.h", gen_crc(pv), sha)
    write("vec_frames.h", gen_frames(pv), sha)
    write("vec_streams.h", gen_streams(pv), sha)
    write("vec_check.h", gen_check(jsons["check_vectors"], dic), sha)
    write("vec_units.h", gen_units(jsons["units_vectors"]), sha)
    write("vec_names.h", gen_names(), sha)
    write("vec_motion.h", gen_motion(jsons["motion_vectors"]), sha)
    print(f"gen_test_vectors: ICD {icd}, hash 0x{h:08X}: {len(pv['crc16'])} crc, {len(pv['frames'])} "
          f"frames, {len(pv['streams'])} streams, {len(jsons['check_vectors']['vectors'])} check, "
          f"{len(jsons['units_vectors']['um_to_steps'])}+{len(jsons['units_vectors']['steps_to_um'])}+"
          f"{len(jsons['units_vectors']['rate_cap'])} units, {len(jsons['motion_vectors']['cases'])} motion "
          f"cases -> {OUT_DIR}")


main()
if _SCONS:
    env.Append(CPPPATH=[OUT_DIR])  # noqa: F821
